spring:
  profiles:
    active:
    - cloud
  application:
    name: test
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    ROOT: INFO
    org.springframework.jdbc: DEBUG